### ISSUE TITLE
Audio attribute will reload even if you add data-turbo-permanent

### ISSUE THREAD

**Issue by Jerimu** [tonysm/turbo-laravel#31]
Hi, im trying to add a data-turbo-permanent to an audio element.
But when i click on any <a> attribute the audio restarts and the old one stays on the page and because off this you will hear the audio multiple times. Also tried data-turbo="false"

Somebody any idea how to fix this? (Searched for a discord for support but couldn't find it)

**Comment by tonysm** [comment]
The `data-turbo-permanent` requires an `id` field (so Turbo knows which field to keep between the re-renders). Have you provided that attribute? Something like this:

```html
<audio data-turbo-permanent id="audio-player"></audio>
```

Here's the [documentation about it](https://turbo.hotwired.dev/handbook/building#persisting-elements-across-page-loads).

I'm closing this issue because it doesn't look like an issue with the package itself. If you disagree, please, feel free to reopen it and, please, provide more information about the problem you're having. Cheers.
