### ISSUE TITLE
Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'window.Alpine.version')

### ISSUE THREAD

**Issue by vmiguellima** [tonysm/turbo-laravel#34]
This error appear when using Laravel Livewire:

```
Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'window.Alpine.version')
```

To Solve it simply, add to `resources/js/libs/alpine.js`:
```js
window.Alpine = Alpine;
```

After:
```js
import Alpine from 'alpinejs';
```

Final  `resources/js/libs/alpine.js` file:
```js
import Alpine from 'alpinejs';

window.Alpine = Alpine; // <---- Added Here

document.addEventListener('turbo:before-render', () => {
    let permanents = document.querySelectorAll('[data-turbo-permanent]')

    let undos = Array.from(permanents).map(el => {
        el._x_ignore = true

        return () => {
            delete el._x_ignore
        }
    })

    document.addEventListener('turbo:render', function handler() {
        while(undos.length) undos.shift()()

        document.removeEventListener('turbo:render', handler)
    })
})

Alpine.start();

export default Alpine;
```

**Comment by tonysm** [comment]
Hey, thanks for the issue. I've [already changed](https://github.com/tonysm/turbo-laravel/blob/main/stubs/resources/js/libs/alpine.js#L18-L20) the default scaffolding for Alpine due to the recent fix that was shipped in Alpine (with the new LW bridge). So this should be fixed on new installs.

For everyone facing this, you can fix it just like @vmiguellima did. Just make sure the window assignment happens before the start call. Not sure why, but I was getting weird errors when assigning to the window after calling the start method.

Thanks @vmiguellima for posting your fix!
