### ISSUE TITLE
[Question] @domid() directive behaviours and conventions

### ISSUE THREAD

**Issue by tortuetorche** [tonysm/turbo-laravel#4]
Hi @tonysm,

Firstofall, many thanks for this great package 👍

I want to exchange with you about the `@domid()` Blade directive behaviours and conventions.

## Sub Models
If you have a model in a sub folder/sub namespace, it doesn't work like the `dom_id()` helper of Rails.
Here an use case:
```blade
<?php
// app/Models/Account/User.php
namespace App\Models\Account;

use App\Models\User as BaseUser;

class User extends BaseUser
{
    //...
}
```

In a blade view:
```blade
@domid(App\Models\Account\User::first())
```

Should return `account_user_1`, like Rails does.
But it returns `user_1`, so you can have some collision with other elements in your page.

## New record/model
In Rails when you do in your view:
```erb
<%= dom_id(User.new) %>
```
It returns `new_user`.
The `new_` prefix is a Rails convention which is _linked_ to the `UsersController.new()` action.

But in Laravel we have instead of the `new` action the `create` action, like this : `App\Http\Controllers\UsersController::create()`.
So it'll be convenient to return `create_user` when using the `@domid()` Blade directive with a new Model.
To summary, in a blade view:
```blade
@domid(new App\Models\User)
```
Should return `create_user`.
But it returns `user_` with the current version of your package.

--------

By the way, I'm the creator of the package [jQuery Laravel](https://github.com/efficiently/jquery-laravel) which is a port of Rails <abbr title="Unobtrusive JavaScript">UJS</abbr> for Laravel, so I look into Rails VS Laravel conventions since few years 😅

And I already ported the `dom_id()` helper for Laravel, feel free to borrow my own implementation: https://github.com/efficiently/jquery-laravel/blob/2.5/src/Efficiently/JqueryLaravel/EloquentHtmlHelper.php

Have a good day,
Tortue Torche

**Comment by tonysm** [comment]
There was an untagged fix related, so new model instances should create a `user_new` (see the tests [here](https://github.com/tonysm/turbo-laravel/blob/main/tests/Views/ViewHelpersTest.php#L37)), but I see your point.

Related to your suggestion to take more parts of the namespace in consideration.. kinda tricky. I think we can default to stripping out the namespace root (either `App\\` or `App\\Models` when the `app/Models` folder exists) and allow overriding this logic somewhere. I think Laravel implementated something like this before. Not sure how Rails handles models outside of the `app/models` folder, for instance. What would the DOM ID be in those cases?

I'm going to take a look at your implementation, I think I like to use `create` instead of `new` to adhere to the resource conventions in Laravel better. And I'll try implementing prefixing instead of suffixing.

Also, feel free to contribute, if you have the time!

_PS_: I've been missing Rails UJS when trying to use Turbolinks in Laravel, like, forever. Nice package!

**Comment by tortuetorche** [comment]
> Not sure how Rails handles models outside of the `app/models` folder, for instance. What would the DOM ID be in those cases?

I created a `app/external.rb` model and also a `app/sub/external.rb` model and the `dom_id()` results are:
* For a new instance of the `External` model: `new_external`
* For a new instance of the `Sub::External` model: `new_sub_external`

So it works 👍, but I don't think many Rails developpers put their models outside the `app/models` directory

>Also, feel free to contribute, if you have the time!
>PS: I've been missing Rails UJS when trying to use Turbolinks in Laravel, like, forever. Nice package!

Thank you Tony and yes I'll try to contribute on this project 🤞

**Comment by tonysm** [comment]
Hey, so I made some changes to the DOM ID generation. It now:

- Returns `create_{$resource}` instead of `{$resource}_new` for new model instances (still uses the prefix)
- Strips out only the root namespaces of the model's FQCN. The root namespaces are configurable, so if anyone is using non-conventional namespaces, they should add their namespaces to the `turbo-laravel.models_namespace` config key. This way, we will respect nested-namespaces for models unside a sub folder (`App\\Models\\Account\\User` will generate `account_user_id` for existing instances and `create_account_user` for new instances, for example)
- There is also a namespaced function `dom_id` that can be used outside of views

**Comment by tonysm** [comment]
Let me know what you think. Will close the issue for now. Feel free to re-open if you think it can be improved/changed.
