### ISSUE TITLE
Multistep form with turbo frame

### ISSUE THREAD

**Issue by odion-cloud** [tonysm/turbo-laravel#44]
is there a way to create multistep form with turbo frame

**Comment by tonysm** [comment]
I don't think there's much difference than implementing a multistep form without Turbo Frames, honestly. You'd have views for each step, validate each step submission, store the "in progress" data in session when valid (or display the same step form with the invalid messages), then you'd combine the data once the last step is submitted valid.

The only difference would be that the views would use the same Turbo Frame ID, so when they are submitted, only the frame would be replaced with another frame. The trick is to redirect (even if it's a redirect to the same controller&action with different query strings, such as `?step=2`). And return invalid responses with a 422.

Here's an example:

```php
class RegistrationController extends Controller
{
  const STEP_PROFILE = 'profile';
  const STEP_ADDRESS = 'address';
  const STEP_CONTACT_INFO = 'contact';
  const STEP_FINISHED = 'finished';

  const STEPS_RULES = [
    self::STEP_PROFILE => [
      'name' => ['required', 'string'],
    ],
    self::STEP_ADDRESS => [
      'street_address' => ['required', 'string'],
    ],
    self::STEP_CONTACT_INFO => [
      'email' => ['required', 'email', 'unique:users,email',
    ],
  ];

  public function create(Request $request)
  {
    return view('registration.create', [
      'step' => $this->currentStep($request),
    ]);
  }

  public function store(Request $request)
  {
    $currentStep = $this->currentStep($request);
    $rules = self::STEPS_RULES[$currentStep];

    // Validate each step, if invalid, it will render the form again (default Turbo Laravel behavior).
    $data = $request->validate($rules);

    $nextStep = match ($currentStep) {
      self::STEP_PROFILE => self::STEP_ADDRESS,
      self::STEP_ADDRESS => self::STEP_CONTACT_INFO,
      default => self::STEP_FINISHED,
    };

    if ($nextStep === self::STEP_FINISHED) {
      // This is the last stepCreate the profile using current request data and the things in session...
      // Make sure you delete the step from session:

      $request->session()->remove('step');

      return redirect()->route('registration.success');
    }

    // Store the data in session to be used in the last step...
    $request->session()->put('step', $nextStep);

    // On success, redirect back to the create.
    return redirect()->route('registrations.create');
  }
  
  private function currentStep(Request $request): string
  {
    return $request->session()->get('step', self::STEP_PROFILE);
  }
}
```

(sorry, code is a little messy, but it's just a proof of concept)

The view would look something like this:

**resources/views/registration/create.blade.php**
```blade
<turbo-frame id="registration">
  @include('registration._' . $step)
</turbo-frame>
```

Since you're passing the step string to the view, you'd need one _partial_ for each step, so things like:

| Step | Partial |
|---|---|
| `'profile'` | `resources/views/registration/_profile.blade.php` |
| `'address'` | `resources/views/registration/_address.blade.php` |
| `contact` | `resources/views/registration/_contact.blade.php` |

All these partials would have a form. The last one (`_contact.blade.php`) would have a `data-turbo-frame="_top"` in the form itself, which means when it successfully submits, the entire page will redirect to the success location. When submitted with invalid data, it should just replace the frame with the same form again, but with the invalid messages.

---

Sorry for the long message, but this should give an idea of how you could implement it. I haven't tested this code, but again, it's just an overview on how you could achieve.

I might record a screencast soon as this is an interesting topic (and a very common one).

Let me know if this was helpful. For now, I'm closing the issue for now. Also, I think it would be a good idea to post a message in the [Hotwired Discussion](https://discuss.hotwired.dev/) forum about it, as you may gain more insights there.
