### ISSUE TITLE
How to publish generated turbo js in my HTML 

### ISSUE THREAD

**Issue by stevebrainng** [tonysm/turbo-laravel#55]
Hello I have installed the package. everything went well with the installation, but I can't get the Plugin working on the frontend...
I'm not using LiveWire and I just want to only use it on Laravel Blade with Html. How do I incllude the Script to my Layout.app blade file?
the docs skipped that part.

Please help

**Comment by tonysm** [comment]
@stevebrainng 

The `turbo:install` command was built with a fresh Laravel app in mind. It's not required to have Livewire installed to use the command, only if you pass the `--jet` flag, which assumes you're using Laravel with Jetstream/Livewire stack.

In other words, if you have a fresh Laravel application that doesn't use Livewire, I'd recommend running `php artisan turbo:install` or even `php artisan turbo:install --stimulus` if you want to get Stimulus installed as well.

If you're using [Laravel Mix](https://laravel.com/docs/9.x/mix#installation), you should be all set after a `npm install && npm run dev`. If not, then you should add the script and styles from Laravel mix (see docs):

For your scripts:

```blade
<script src="{{ mix('/js/app.js') }}"></script>
```

And for your styles:

```blade
<link href="{{ mix('/css/app.css') }}" rel="stylesheet">
```

---

If you're curious, you can check out the source of the command [here](https://github.com/tonysm/turbo-laravel/blob/main/src/Commands/TurboInstallCommand.php), but the gist is:

1. It adds the correct NPM dependencies to your `package.json` file ([lines](https://github.com/tonysm/turbo-laravel/blob/main/src/Commands/TurboInstallCommand.php#L19-L46))
2. It tweaks your JS file structure a bit:
    1. Ensures there's a `resources/js/elements/` folder where the new Turbo Stream Echo Source custom HTML component will be added
    2. Ensures there's a `resources/js/libs/` folder where a `turbo.js` file will be added
    3. Copies over the suggested `app.js` file to `resources/js/app.js` (replaces existing one if any)
    4. Copies over the suggested `turbo.js` file to the `resources/js/libs/turbo.js` location (replaces if exists)
    5. Copies over the suggested `turbo-stream-echo-tag.js` file to `resources/js/elements/turbo-stream-echo-tag.js` (replaces if it exists)
    6. Copies over the suggested `bootstrap.js` file to `resources/js/bootstrap.js` (replaces if exists)

You can check the suggested JS structure [here](https://github.com/tonysm/turbo-laravel/tree/main/stubs/resources/js).

---

Closing the issue because I think there's nothing else for me to say here. If you're still having problems, feel free to re-open the issue and let me know (ping me).
