### ISSUE TITLE
Turbo-stream - WithErrors

### ISSUE THREAD

**Issue by ekrist1** [tonysm/turbo-laravel#57]
Would it be possible to chain the turbostream response with withErrors, like the example?  

`return response()->turboStream()
    ->target('comments')
    ->action('append')
    ->view('comments._comment', ['comment' => $comment])
->withErrors(["your_custom_error"=>"Your custom error message!"]);
`

**Comment by ekrist1** [comment]
I figured out how to stream errors to a turbo stream: [https://www.youtube.com/watch?v=9uwIJmIaSXU](url)

Seems like the code it's a bit cleaner using Rails. Here is how I solve it with Laravel at the moment:

`   $validator = Validator::make($request->all(), [
            'email' => 'required', 'email',
            'password' => 'required',
        ]);

        if ($validator->fails()) {
            return response()->turboStream()
                ->target('auth-error')
                ->action('update')
                ->view('components.turbo-auth-validation-errors', ['error' => 'Feil passord eller brukernavn']);
        }`

**Comment by tonysm** [comment]
@ekrist1 

In the video you shared they put the Turbo Stream building into view, you could do that as well:

```php
$validator = Validator::make(...);

if ($validator->fails()) {
  return response()->turboStreamView('auth.turbo.validation_error', [
    'error' => 'Feil passord eller brukernavn',
  ]);
}
```

Then you would have to create a view under `resources/views/auth/turbo/validation_error.blade.php` with the following contents:

```blade
<x-turbo-stream action="update" target="auth-error">
  @include('components.turbo-auth-validation-errors', ['error' => $error])
</x-turbo-stream>
```

I think this version is more on par with what happens in the video. Not sure which version is better in this case.

I assume you want to return a Turbo Stream for a specific page, not for everywhere you're dealing with validation. For the "normal" case, I'd recommend using Resource Routes as much as possible, or at least try to stick to the conversion of showing a form in a route named `*.create` and having the handling endpoint route named `*.store` (or `*.edit` and `*.update`). More about that in [the documentation](https://github.com/tonysm/turbo-laravel#redirects).

The Ruby code seems "smaller", but that's due to syntax and more conventions than Laravel has for figuring out which views to render.

Closing the issue now because the issue seems to have been solved. Feel free to re-open if you think there's an issue here or if you want to suggest an API that could improve the experience here.
