### ISSUE TITLE
Select contents of input after clicking on edit

### ISSUE THREAD

**Issue by bilogic** [tonysm/turbo-laravel#67]
Hi!

Not sure where to ask this, appreciate if you can help.

Supposed I have a button to edit, is it possible (to run some javascript) to select all text in the input box via TurboStream after clicking to edit?
Or is Stimulus the only way? Thank you!

**Comment by tonysm** [comment]
Not sure I follow. Can you clarify the use case? Feel free to ask here, but I'll close the issue for now as this is not related to package.

**Comment by bilogic** [comment]
Ok

1. Let's say I have some text in a turbo frame that can be clicked on to edit, i.e. clicking turns it into a form with an `<input>` that is filled with the text
2. When it turns into a form, the `<input>` is not focused
3. How can I get it to focus?
4. To go even further, how can I get the text in the `<input>` to be selected? i.e. the effect of pressing `ctrl+a` while in the `<input>`
5. Is Stimulus the only way? My issue with Stimulus is the need for `npm i && npm run dev`, and my initial impression was it would be a thing of the past after I'm fully in on Turbo. (unfortunately not... haha)

Just like to add that I already managed to get infinite scrolling to work using a Stimulus controller

Thanks!

**Comment by tonysm** [comment]
So, if you have an autofocus attribute in your input, Turbo will find the first one with that attribute and focus it for you. Something like `<input autofocus ... />`.

If you want to _select_ the content, you're gonna need JavaScript, since that's a browser thing. Hotwire is really about using [the rule of least power](https://www.w3.org/2001/tag/doc/leastPower.html) to do the job, but sometimes we need JavaScript. I would add a Stimulus controller for that like:

```js
// resources/js/controllers/select_all_controller.js
import { Controller } from '@hotwired/stimulus';

export default class extends Controller {
  connect() {
    this.element.select();
  }
}
```

So your input would be like:

```html
<input autofocus data-controller="select-all" />
```

Something like that (I haven't tested this, it's just what I would try).

About needing NPM, yeah, I feel the pain. That's why I built the [Importmap Laravel](https://github.com/tonysm/importmap-laravel) package. Here's [an intro if you're interesting](https://youtu.be/3P_h7zWY1pU). The idea is to stay in PHP as much as I can

**Comment by bilogic** [comment]
Yes, I have seen your importmap, it will be the next thing once I reach my milestones with the Turbo integration.

I have tried `autofocus` a few days ago, it only works on the 1st turbo stream, subsequent ones don't `autofocus`. I did not pursue further.

Do you mean that with importmap, I can still write controllers for Stimulus? That would be an acceptable trade off.

**Comment by tonysm** [comment]
@bilogic Yep. The [demo app](https://github.com/tonysm/turbo-demo-app/blob/main/routes/importmap.php) uses Importmap and makes use of Alpine, Stimulus, and other JS libs.
