### ISSUE TITLE
Why does response()->turboStreamView() expect a view instance?

### ISSUE THREAD

**Issue by georgeboot** [tonysm/turbo-laravel#7]
While playing around with this (awesome) package, I noticed the following:

```php
return response()->turboStreamView(view('comments.turbo_created_stream', [
  'comment' => $comment,
]));
```

What is the reason you expect a view instance as the argument, and not just the view name + data? This feels way more natural to me.

**Comment by tonysm** [comment]
That's because I don't want to replicate the functionality in Laravel itself. I would agree the naming looks off, so something like `turboStreamUsing(view())` might read better?

Personally, I use PHPStorm, and the macros, while they are great, I don't get auto-completion, so I wanted to limit the about of "unkowns" or conventions using the package. I'll test it out again here to see if the auto-completion thing works with macros.

**Comment by georgeboot** [comment]
Perhaps the most Laravel way of doing this, is t do a `is_string($view)`. If true, wrap it in a view call with the optional second argument.

**Comment by tonysm** [comment]
Added an alternative syntax to the `turboStreamView` helper. Checkout the [docs](https://github.com/tonysm/turbo-laravel/blob/main/docs/02-OVERVIEW.md#turbo-stream-view).
