### ISSUE TITLE
Handling HTTP 419

### ISSUE THREAD

**Issue by bilogic** [tonysm/turbo-laravel#72]
There might be instances where a turbo POST to the server returns 419 due to various reasons, e.g. expired token etc. 

Turbo just replaces the frame with a empty HTML. I think it would be more correct to refresh the page as a whole.

**Comment by tonysm** [comment]
That's up to the application developers. You can listen for the [Turbo events](https://turbo.hotwired.dev/reference/events) and decide what happens when a `turbo:submit-end` fails or not.

In my demo app, I needed to add the CSRF token to the Turbo requests ([source](https://github.com/tonysm/turbo-demo-app/blob/main/resources/js/bootstrap.js#L19-L29)), that I think I can pull into the package setup.

**Comment by tonysm** [comment]
Actually, that snippet was already added to the package [here](https://github.com/tonysm/turbo-laravel/blob/main/stubs/resources/js/bootstrap.js#L45-L53)
