### ISSUE TITLE
Validation errors visible on second visit

### ISSUE THREAD

**Issue by martin-ro** [tonysm/turbo-laravel#80]
I noticed if you try to log in with an incorrect password, navigate away from the login page, and then back to it you'll see the previous validation error for a split second. I first noticed that in my own app but the described behavior can also be observed in the demo app.

Is there any way to fix this?

Cheers

**Comment by tonysm** [comment]
Hey, @martin-ro 

That's because Turbo will first show the page from the cache while it fetches a new version of the page, then replaces it. If you don't want certain items to be stored in the cached HTML (such as flash messages), make sure you annotate them with `data-turbo-cache="false"`. You can also manipulate the DOM right before it's cached by listening to the `turbo:before-cache` and, say, close a modal that is open or remove an `invalid` CSS class from form elements, things like that. See the [docs](https://turbo.hotwired.dev/handbook/building#preparing-the-page-to-be-cached).

**Comment by martin-ro** [comment]
Thanks, `data-turbo-cache="false"` seems to do the trick in this case.
